<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="12" failed="4" ignored="0" total="26" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="8450" started-at="2019-01-05T09:04:20Z" finished-at="2019-01-05T09:04:28Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="8450" started-at="2019-01-05T09:04:20Z" finished-at="2019-01-05T09:04:28Z">
      <class name="com.testapi.casev.Testapi">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="beforeTest" is-config="true" duration-ms="10" started-at="2019-01-05T09:04:20Z" finished-at="2019-01-05T09:04:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="416" started-at="2019-01-05T09:04:20Z" data-provider="DP1" finished-at="2019-01-05T09:04:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！1'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="445" started-at="2019-01-05T09:04:21Z" data-provider="DP1" finished-at="2019-01-05T09:04:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！2'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="82" started-at="2019-01-05T09:04:21Z" data-provider="DP1" finished-at="2019-01-05T09:04:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！3'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="105" started-at="2019-01-05T09:04:22Z" data-provider="DP1" finished-at="2019-01-05T09:04:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！3'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="1521" started-at="2019-01-05T09:04:22Z" data-provider="DP1" finished-at="2019-01-05T09:04:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！3'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="FAIL" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="419" started-at="2019-01-05T09:04:23Z" data-provider="DP1" finished-at="2019-01-05T09:04:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！3'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="39" started-at="2019-01-05T09:04:24Z" data-provider="DP1" finished-at="2019-01-05T09:04:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！4'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="45" started-at="2019-01-05T09:04:24Z" data-provider="DP1" finished-at="2019-01-05T09:04:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！4'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="58" started-at="2019-01-05T09:04:24Z" data-provider="DP1" finished-at="2019-01-05T09:04:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！4'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="FAIL" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="300" started-at="2019-01-05T09:04:24Z" data-provider="DP1" finished-at="2019-01-05T09:04:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！4'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="30" started-at="2019-01-05T09:04:24Z" data-provider="DP1" finished-at="2019-01-05T09:04:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！5'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="34" started-at="2019-01-05T09:04:24Z" data-provider="DP1" finished-at="2019-01-05T09:04:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！5'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="385" started-at="2019-01-05T09:04:25Z" data-provider="DP1" finished-at="2019-01-05T09:04:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！5'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="FAIL" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="1066" started-at="2019-01-05T09:04:25Z" data-provider="DP1" finished-at="2019-01-05T09:04:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！5'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="50" started-at="2019-01-05T09:04:26Z" data-provider="DP1" finished-at="2019-01-05T09:04:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！6'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="34" started-at="2019-01-05T09:04:26Z" data-provider="DP1" finished-at="2019-01-05T09:04:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！6'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="21" started-at="2019-01-05T09:04:26Z" data-provider="DP1" finished-at="2019-01-05T09:04:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！6'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="FAIL" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="18" started-at="2019-01-05T09:04:26Z" data-provider="DP1" finished-at="2019-01-05T09:04:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！6'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4001] but found [4000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4001] but found [4000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testapi.casev.Testapi.f(Testapi.java:41)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="15" started-at="2019-01-05T09:04:26Z" data-provider="DP1" finished-at="2019-01-05T09:04:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！7'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="398" started-at="2019-01-05T09:04:26Z" data-provider="DP1" finished-at="2019-01-05T09:04:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！8'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="65" started-at="2019-01-05T09:04:27Z" data-provider="DP1" finished-at="2019-01-05T09:04:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！9'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="95" started-at="2019-01-05T09:04:27Z" data-provider="DP1" finished-at="2019-01-05T09:04:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！10'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="783" started-at="2019-01-05T09:04:27Z" data-provider="DP1" finished-at="2019-01-05T09:04:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！11'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="506" started-at="2019-01-05T09:04:28Z" data-provider="DP1" finished-at="2019-01-05T09:04:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！12'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="84" started-at="2019-01-05T09:04:28Z" data-provider="DP1" finished-at="2019-01-05T09:04:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！13'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="f" duration-ms="32" started-at="2019-01-05T09:04:28Z" data-provider="DP1" finished-at="2019-01-05T09:04:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.tuling123.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/openapi/api/v2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[POST]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{'key':'你好！14'}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.testapi.casev.Testapi@55f3ddb1]" name="afterTest" is-config="true" duration-ms="1" started-at="2019-01-05T09:04:28Z" finished-at="2019-01-05T09:04:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.testapi.casev.Testapi -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
